name: alphabetmitrawand
description: AlphabetMitRawand is a mobile app and web-app to learn German in the best and easy way.

publish_to: 'none'

version: 1.0.0+beta

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  url_strategy: ^0.2.0
  drop_shadow_image: ^0.9.1
  smooth_page_indicator: ^1.0.0+2
  shared_preferences: ^2.0.17
  url_launcher: ^6.1.9
  flutter_web_browser: ^0.17.1
  share_plus: ^6.3.0
  flutter_local_notifications: ^13.0.0
  flutter_kurdish_localization: ^1.0.1
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  cloud_firestore: ^4.3.2
  connectivity: ^3.0.6
  flutter_offline: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/logo/
    - assets/json/



  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato.ttf
    - family: NotoSansKurdish
      fonts:
        - asset: assets/fonts/NotoSansKurdish.ttf
        - asset: assets/fonts/NotoSansKurdish-Bold.ttf
          weight: 700