// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2DV_uHq6lGbP8hl_XNVyRdPcc1f65Ss',
    appId: '1:422185554814:web:9ff76a73b63ca82653592f',
    messagingSenderId: '422185554814',
    projectId: 'alphabet-mit-rawand',
    authDomain: 'alphabet-mit-rawand.firebaseapp.com',
    storageBucket: 'alphabet-mit-rawand.appspot.com',
    measurementId: 'G-JYTJ7P64W1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBArAbz1_aUQUO5aEBD-ibLc2vPP99KVO4',
    appId: '1:422185554814:android:305aba1c8dc0e1bc53592f',
    messagingSenderId: '422185554814',
    projectId: 'alphabet-mit-rawand',
    storageBucket: 'alphabet-mit-rawand.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg6G382pzVL6uY99fazhKVR_FW1O4xaU0',
    appId: '1:422185554814:ios:69b9d5559076b63053592f',
    messagingSenderId: '422185554814',
    projectId: 'alphabet-mit-rawand',
    storageBucket: 'alphabet-mit-rawand.appspot.com',
    androidClientId: '422185554814-11g22p3j8h5j1tem6tf2hlg82d83ihga.apps.googleusercontent.com',
    iosClientId: '422185554814-qgfeak3k99pl5ek7npf8fi57kji8cj8p.apps.googleusercontent.com',
    iosBundleId: 'com.example.alphabetmitrawand',
  );
}
