name: Build APK and IPA v0.0.1

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.4'

    - name: Get packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build IPA
      run: flutter build ios --release --no-codesign

    - name: Upload APK and IPA artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built-app
        path: |
          build/app/outputs/apk/release/app-release.apk
          build/ios/archive/Runner.ipa
