name: Test build

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.4'

    - name: Get packages
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Build Web
      run: flutter build web --release
        
    - name: Deploy to Github Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.UPLOAD_WEB }}
        publish_dir: build/web
          target_branch: web
          cname: alphabetmitrawand.github.io/AlphabetMitRawand/